name: sf_symbols
description: A new Flutter package project.
version: 0.0.2
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^5.0.2
  dart_style: ^2.3.2
  args: ^2.4.2
  path: ^1.8.3
  cli_util: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

  # fonts:  
  #   - family: SF Pro
  #     fonts:
  #       - asset: fonts/SF-Pro/SF-Pro.ttf
  #         style: normal
  #       - asset: fonts/SF-Pro/SF-Pro-Italic.ttf
  #         style: italic
  #   - family: SF Compact
  #     fonts:
  #       - asset: fonts/SF-Compact/SF-Compact.ttf
  #         style: normal
  #       - asset: fonts/SF-Compact/SF-Compact-Italic.ttf
  #         style: italic
    # - family: SF Mono
    #   fonts:
    #     - asset: fonts/SF-Mono/SF-Mono-Light.otf
    #       style: normal
    #       weight: 300
    #       # weight: 274
    #     - asset: fonts/SF-Mono/SF-Mono-LightItalic.otf
    #       style: italic
    #       weight: 300
    #       # weight: 274
    #     - asset: fonts/SF-Mono/SF-Mono-Regular.otf
    #       style: normal
    #       weight: 400
    #     - asset: fonts/SF-Mono/SF-Mono-RegularItalic.otf
    #       style: italic
    #       weight: 400
    #     - asset: fonts/SF-Mono/SF-Mono-Medium.otf
    #       style: normal
    #       weight: 500
    #       # weight: 510
    #     - asset: fonts/SF-Mono/SF-Mono-MediumItalic.otf
    #       style: italic
    #       weight: 500
    #       # weight: 510
    #     - asset: fonts/SF-Mono/SF-Mono-Semibold.otf
    #       style: normal
    #       weight: 600
    #       # weight: 590
    #     - asset: fonts/SF-Mono/SF-Mono-SemiboldItalic.otf
    #       style: italic
    #       weight: 600
    #       # weight: 590
    #     - asset: fonts/SF-Mono/SF-Mono-Bold.otf
    #       style: normal
    #       weight: 700
    #     - asset: fonts/SF-Mono/SF-Mono-BoldItalic.otf
    #       style: italic
    #       weight: 700
    #     - asset: fonts/SF-Mono/SF-Mono-Heavy.otf
    #       style: normal
    #       weight: 900
    #       # weight: 860
    #     - asset: fonts/SF-Mono/SF-Mono-HeavyItalic.otf
    #       style: italic
    #       weight: 900
    #       # weight: 860